version: '3'

volumes:
    postgres: ~

services:
    db:
        image: postgres:15.2-alpine
        volumes:
            - "postgres:/var/lib/postgresql/data"
        environment:
            POSTGRES_DB: dbname
            POSTGRES_USER: username
            POSTGRES_PASSWORD: password
        ports:
            - "54329:5432"
